---
dependencies:
  - page: https://raw.githubusercontent.com/nkbinnovations/reusable-workflows/main/README.md
    path: content/projects/reusable-components/github/workflows/workflows.md
    title: 'Reusable Workflows'
  - page: https://raw.githubusercontent.com/nkbinnovations/reusable-actions/main/README.md
    path: content/projects/reusable-components/github/actions/actions.md
    title: 'Reusable Actions'
  - page: https://raw.githubusercontent.com/nkbinnovations/terraform-aws-iam-roles-module/refs/heads/main/README.md
    path: content/projects/terraform-modules/aws/iam-role.md
    title: 'IAM Roles'
