---
name: pre-commit-checks
run-name: "${{ github.actor }} has triggered the pre-commit-checks"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: '3.13.0'
      - name: Install python dependencies
        run: |-
          python -m pip install -r requirements.txt
      - name: Run pre-commit
        run: |-
          pre-commit run --all-files --verbose
        env:
          ANSIBLE_ROLES_PATH: "${{ github.workspace }}/ansible/roles:${HOME}/.ansible/roles"
          ANSIBLE_CONFIG: "${{ github.workspace }}/ansible/ansible.cfg"
